project:
  type: website
  output-dir: docs

website:
  title: "Kyle Hansen"
  site-url: https://kylhansen.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - teaching/index.qmd
      - scholarship.qmd
      - outreach.qmd
      - about.qmd
      - text: Other
        menu: 
        - href: posts.qmd
          text: Blog
        - href: lunch.qmd
  
  page-footer: 
    center:
      - text: "\"The moving power of mathematical invention is not reasoning, but imagination.\" —Augustus De Morgan"
    border: true
    background: $primary


format:
  html:
    respect-user-color-scheme: true
    theme: 
      light: 
        - flatly
        - sty/light.scss
      dark: 
        - darkly
        - sty/dark.scss
    css: sty/styles.css
    toc: true
    toc-location: right 

date-format: iso
title-block-banner: true