---
title: "Research"
---

## Quantitative Topology

## Tiling Spaces

---

Ignore the mess below this line for now

---

If you want to study the complexity of a topological space, you might study the algebraic invariants of this space.
Often, however, topological spaces such as manifolds come equipped with some geometric structure as well. 
How does this algebraic topological complexity translate into geometric complexity?
This broad question motivates the field of so-called "quantitative topology".

For example, if you have a nullhomotopic map (a priori, algebraic information) into your space, what is the most efficient way to perform this nullhomotopy (geometric information)?
My advisor Fedya Manin has asked (and answered) similar questions in the context of simpy connected target spaces, and some of my current work is an extension of this to nilpotent targets.

I also study tiling spaces, where I am interested in extending some existing theory to the relevant nilpotent setting. 
For example, I extend work about the topology of Euclidean tiling spaces to tiling spaces of certain nilpotent Lie groups.

I have also studied elliptic manifolds, where I asked "Given a nilpotent Lie group $G$, what algebraic information is necessary/sufficient to guarantee that a closed manifold M is $G$-elliptic?" 
In some sense, this asks which manifolds $M$ can be efficiently wrapped using the group $G$ as your wrapping paper.
Until recently, there has been little indication of how to solve this problem. 
Recent advances in related areas have opened up some clear paths forward in this investigation, where it seems likely that the Heisenberg group is a poor choice of wrapping paper for a flat torus.

### Papers



      <h3>Talks</h3>
      <ul>
        <li>Volumes of Nullhomotopies in Nilpotent Spaces (PhD Defense, 2025/05/07)
          <ul>
            <li><a href="Talks/Volumes-of-Nullhomotopies-defense-2025-05-07.pdf">PDF</a></li>
          </ul>
        </li>
        <li>Mathematical Quasicrystals: The Taming of the Hullabaloo (Undergraduate Colloquium, 2025/02/05)
          <ul>
            <li><a href="Talks/quasicrystals-general-2025-02-05.pdf">PDF</a></li>
          </ul>
        </li>
        <li>Tiling Spaces Which are Fiber Bundles over Nilmanfiolds (41st Workshop in Geometric Topology, 2024/06/13)
          <ul>
            <li><a href="Talks/Tiling-Spaces-Fiber-Bundles-WGT24.pdf">PDF</a></li>
          </ul>
        </li>
        <!-- <li>Tiling Spaces are Fiber Bundles over Nilmanfiolds (UCSB Graduate Topology Seminar, 2/14/2024)
          <ul>
            <li><a href="Talks/Tiling-Spaces-Fiber-Bundles.pdf">PDF</a></li>
          </ul>
        </li> -->
        <li>The Hull of a Manifold with Bounded Geometry (UCSB Topology Seminar, Advancement Talk 2022/05/24)
          <ul>
            <li><a href="Talks/The_Hull_of_a_Manifold_with_Bounded_Geometry.pdf">PDF</a></li>
          </ul>
        </li>
        <li>An Introduction To Tiling Spaces (UCSB Graduate Topology Semniar, 2022/04/06)
          <ul>
            <li><a href="Talks/Intro_to_Tiling_Spaces.pdf">PDF</a></li>
          </ul>
        </li>
      </ul>
      <h3>Other Unpublished Works (definitely not peer-reviewed)</h3>
      <ul>
      <li>Elliptic Curve Cryptography (2021)
        <ul>
          <li><a href="Papers/Elliptic_Curve_Cryptography.pdf">PDF</a></li>
        </ul> 
      </li>
      <li>Much Ado About Nothing, or All For Naught? Investigating the Zeros of Complex Functions (Undergraduate Honors Thesis, 2019)
        <ul>
          <li><a href="Papers/Major_Honors.pdf" target="_none">PDF</a></li>
        </ul>
      </li>
      </ul>
    </p>
  </div>


## 