---
title: "Conferences"
description: "[arXiv](https://arxiv.org/a/0000-0002-8239-8782.html) • [Google Scholar](https://scholar.google.com/citations?user=t20yhwsAAAAJ&hl=en) • [ORCiD](https://orcid.org/0000-0002-8239-8782)"
---

## [Have We Met Before?](https://www.youtube.com/watch?v=YRm9wCuDAcg)

Perhaps you've seen me at one of the following conferences:

### 2026

- *MathFest*, Boston, MA
- *Virtue Education Workshop*, Pepperdine, Malibu, CA
- *Joint Mathematics Meeting*, Washington, DC

### 2025

- *AMS SE Sectional Meeting*, Tulane University, New Orleans, LA
- *MathFest*, Sacramento, CA

### 2024 

- *41st Workshop in Geometric Topology*, Calvin University, Grand Rapids, MI
- *Quantitative Topology and Beyond*, Simons Foundation, New York City, NY
- *Joint Mathematics Meeting*, San Francisco, CA

### 2023

- *Geometry and Analysis of Groups and Manifolds*, Centro De Giorgi, Pisa, Italy
- *Sub-Riemannian Geometry and Beyond III*, Centro De Giorgi, Pisa, Italy
  
### 2022 

- *Graduate Student Concentration Week on Metric Geometry (Workshop in Analysis and Probability)*, Texas A&M, College Station, TX

### 2019
 
- *Joint Mathematics Meeting*, Baltimore, MD